### ISSUE TITLE
Neuer Fehler bei e2 make bre2ze4k 

### ISSUE THREAD

**Issue by Yoshi1981** [mohousch/neutrino2#3]
Hey moh bei e2 ist der Fehler leider wieder 

Already up to date.
==> Applying Patch: enigma2.patch
patching file configure.ac
Hunk #1 FAILED at 35.
1 out of 1 hunk FAILED -- saving rejects to file configure.ac.rej
patching file data/fonts/Makefile.am
Hunk #1 FAILED at 14.
1 out of 1 hunk FAILED -- saving rejects to file data/fonts/Makefile.am.rej
patching file lib/base/estring.cpp
Hunk #1 succeeded at 1104 (offset 169 lines).
patching file lib/dvb/streamserver.cpp
patching file lib/gui/elistboxcontent.cpp
Hunk #1 FAILED at 469.
1 out of 1 hunk FAILED -- saving rejects to file lib/gui/elistboxcontent.cpp.rej
patching file lib/service/Makefile.inc
Reversed (or previously applied) patch detected!  Assume -R? [n] 

Danke dir mfg

**Comment by KittyBua** [comment]
P.s. habe das entfernt und geht weiter 

https://github.com/mohousch/buildsystem/blob/master/make/enigma2.mk#L54

Aber dann kommt ein Fehler später bei Line 72 

No package found sigc++-3.0 

Schade damals ging es noch mit meine Anpassung 2022 :( aber ist ja Experimental

Habe ein Tux Experimental auch gebaut heute geht über mein git zum bauen Tux Experimental mfg
